on: [workflow_dispatch]

jobs:
  dummy_job:
    runs-on: ubuntu-latest
    name: Dummy Job
    steps:
      - name: Dummy Step
        id: id
        uses: Zhiyuan-Amos/DummyGitHubAction
        with:
          inline-variable: 'a'
          configuration-variable: 'b'
