on:
  workflow_dispatch:
    inputs:
      inline-variable:
        required: true
        type: string

jobs:
  dummy_job:
    runs-on: ubuntu-latest
    name: Dummy Job
    steps:
      - name: Dummy Step
        id: id
        uses: Zhiyuan-Amos/DummyGitHubAction@main
        with:
          inline-variable: ${{ inputs.inline-variable }}
          configuration-variable: ${{ secrets.CONFIGURATIONVARIABLE }}
