on:
  workflow_dispatch:
    inputs:
      inline-variable:
        required: true

jobs:
  dummy_job:
    runs-on: ubuntu-latest
    name: Dummy Job
    steps:
      - name: Dummy Step
        id: id
        uses: Zhiyuan-Amos/DummyGitHubAction@main
        with:
          inline-variable: ${{ env.INPUT_INLINE-VARIABLE }}
          configuration-variable: ${{ secrets.CONFIGURATIONVARIABLE }}
